### PR TITLE
fix image issue

### PR DESCRIPTION
**Pull request by henrywangnl**
#22 fixed the image issue

### CODE REVIEW

**Comment by maelle** [comment]
Can you please explain the change? Thanks in any case!

**Comment by henrywangnl** [comment]
As I said in the issue comments, the `media` is a data frame, so
`length(media)` and `seq_along(media)` are not what we want. They just look
for the first two images in a post and replace them with WordPress media
URLs.

This PR literally just use `!Is.null(media)` and `1: nrow(media)` instead.

Hope it's clear enough.

**Comment by maelle** [comment]
oooh sorry now i got it, good catch!! And so this fixes your issue?

Can you change your role in DESCRIPTION from ctb to aut? 

I'll merge tomorrow. Thanks a ton!

**Comment by henrywangnl** [comment]
> oooh sorry now i got it, good catch!! And so this fixes your issue?
> 
> Can you change your role in DESCRIPTION from ctb to aut?
> 
> I'll merge tomorrow. Thanks a ton!

Yes, the issue is fixed and I changed my role :-)
Thanks!

**Comment by maelle** [comment]
Thanks a ton and well done!

**Pull request merged**
