### PR TITLE
encoding

### LINKED ISSUE #26: Encoding
Hi!
Thanks a lot for your work, I just have a problem with encoding when publishing, where all the `'` become `â€™` for instance. And as a french guy, all my accents become nonsense. I suspect that it is a charset/encoding problem but I don't know how to resolve it. I tried to put `encoding: UTF-8` in the YAML but it didn't change. I checked that my Wordpress DB is in UTF-8 to.
The text is bugged when arriving on wordpress, as when editing the code, the `â€™` are hardcoded.
Do you have an idea?

### PR DESCRIPTION
**Pull request by maelle**
Fix #26 

@achateigner this corresponds to your fix I think. Now I wonder how to document the encoding argument, especially I wonder when that will be needed (and whether the default should really be UTF-8 :thinking: ).

Any insight will be appreciated, and as I have little time, I won't merge this right away anyway.

### CODE REVIEW

**Comment by achateigner** [comment]
@maelle I believe it corresponds. I think that the default should definitely be in UTF-8 as it is right now the most common encoding in the world, and this is what you want for your encoding. I don't think that you should worry too much about the documentation about it, R only supports specifically UTF-8 and Latin-1, the later being way less universal. Also, mySQL is UTF-8 aware. Maybe you can write `Encoding argument passed to base::readLines, defaults to UTF-8`.

**Comment by maelle** [comment]
What I wonder about is whether how one saved the index.Rmd makes any difference. I'll think about it a bit more. 

@henrywangnl if you use goodpress again would you mind testing this branch to check it doesn't break anything for you? Thanks.

**Comment by henrywangnl** [comment]
Hi Maelle,

Thanks for getting back to me.
You mean reinstall goodpress and see if it works?
I'll let you know how it goes next time I post.

Thanks,
Henry

**Comment by maelle** [comment]
Yes but with `remotes::install_github("maelle/goodpress", ref = "encoding")`.

This won't fix your images issue sadly, I'd just like to know whether it introduces any new bug 😬 No hurry!

**Comment by henrywangnl** [comment]
> Yes but with `remotes::install_github("maelle/goodpress", ref = "encoding")`.
> 
> This won't fix your images issue sadly, I'd just like to know whether it introduces any new bug 😬 No hurry!

Hi @maelle 

I tested it with my new post and it was going well. Didn't see any new bugs.

Thanks,
Henry

**Comment by maelle** [comment]
thanks a lot @henrywangnl

**Pull request merged**
